### PR TITLE
increase parallelization of PPC64 buildbot

### LINKED ISSUE #177: Increase parallelization of PPC64 builds
The server used for AIX PPC64 builds has 16 core (64 hardware threads) and can easily support more parallelization  during the bot tests.

### PR DESCRIPTION
**Pull request by aixtools**
Closes #177 
Increase  parallelization of PPC64 builds

### CODE REVIEW

**Comment by aixtools** [comment]
Yes, looks like this may be a better way. I'll change the PR.

**Comment by aixtools** [comment]
on edelsohn - as that will always be on POWER8, or better - and currently has 64 (logical) cpus. "aixtools" when on POWER6 only has 4 logical cpus - so leaving asis (for now).

**Comment by aixtools** [comment]
We are a week further, and "sadly", imho - the keyword `parallel_tests` is not just test. As @isidentical mentioned - this also affects the parallelization of the build (`make -jXX`) and not just changing the argument for the test phase (make buildbottest).

If there is not a way to change only the argument to the `test phase` - reverting this change may be the better choice.

**Comment by vstinner** [comment]
PRs are welcome, but I don't have the bandwidth to investigate this issue.

**Pull request merged**
