### PR TITLE
Add new AWS worker and two NoGIL builders

### PR DESCRIPTION
**Pull request by itamaro**
1. Add an AWS ubuntu x86-64 buildbot worker 
2. Add a NoGIL refleaks build factory
3. Add two NoGIL builders (standard + refleaks) to newly added AWS worker

### CODE REVIEW

**Comment by vstinner** [comment]
@zware @pablogsal: I'm not subscribed to the python-buildbot mailing list anymore. Did @itamaro contact you to add the worker to the list of workers with its password?

**Comment by pablogsal** [comment]
I have received no email about this

**Comment by vstinner** [comment]
@itamaro: See https://devguide.python.org/testing/new-buildbot-worker/ You should request a password ;-)

**Comment by zware** [comment]
I've talked with Itamar previously, he has a password already (from previously set up worker `itamaro-fedora-x1`).

**Comment by itamaro** [comment]
thanks @vstinner , apologies if I got confused about the process! (I'm trying to work through it with a few workers I'd like to add for NoGIL, so I can later come back to suggest documentation / process improvements)

can you clarify whether I am supposed to go through the mailing list (or GitHub issue?) for every worker I'd like to add? or whether after asking once, I can continue adding workers by sending PRs like this?

**Comment by itamaro** [comment]
fwiw I also have a Windows worker ready to be added after this one goes through :)

**Review by zware — APPROVED** [review]

**Comment by zware** [comment]
> can you clarify whether I am supposed to go through the mailing list (or GitHub issue?) for every worker I'd like to add? or whether after asking once, I can continue adding workers by sending PRs like this?

I'd rather just do it through GitHub.  I added an issue template for adding a worker and updated the devguide page to point to this issue tracker rather than the mailing list :)

**Comment by itamaro** [comment]
> I'd rather just do it through GitHub

one issue per worker, or one issue per "worker group" (e.g. grouped by maintainer)?

**Comment by pablogsal** [comment]
> > I'd rather just do it through GitHub
> 
> 
> 
> one issue per worker, or one issue per "worker group" (e.g. grouped by maintainer)?

I assume one issue per worker to keep things organised, but whatever works best for you as well 😉

**Comment by itamaro** [comment]
opened issue gh-391 for this worker and gh-392 for the Windows worker coming next!

**Comment by zware** [comment]
Finally found a minute to get this merged and deployed.  Thanks!

**Pull request merged**
