### PR TITLE
Update master branch to 3.10

### PR DESCRIPTION
**Pull request by pablogsal**

### CODE REVIEW

**Comment by pablogsal** [comment]
This addresses the custom failures we have with 3.10

**Comment by zware** [comment]
I knew there was something I missed, but managed to forget what it was as soon as I started looking :(.  Thanks, Pablo.

**Comment by vstinner** [comment]
> I knew there was something I missed, but managed to forget what it was as soon as I started looking :(. Thanks, Pablo.

New branches are created infrequently. Maybe add some notes in the README file?

**Comment by pablogsal** [comment]
> Maybe add some notes in the README file?

Yep, I can do a Pr with that.

**Comment by vstinner** [comment]
See also https://github.com/python/peps/issues/1405

**Pull request merged**
