### PR TITLE
gh-560: Add Windows PGO NoGIL builder

### PR DESCRIPTION
**Pull request by itamaro**

### CODE REVIEW

**Comment by itamaro** [comment]
@zware @mdboom is there are no concerns with the implementation, I will merge this tomorrow, when I can keep an eye on the Windows worker more closely.

**Comment by db3l** [comment]
@itamaro, if you could, when you enable this tomorrow, could you specifically take a peek at how test_cext does?

It looks like it's been failing on my new PGO builder.  I haven't had a lot of time to look into it, but from what I can tell it didn't run in the past as it skips debug mode on Windows - but the PGO builder is no longer debug mode.  I didn't notice this during my manual test as I hadn't enabled the "cpu" resource so it didn't even try test_cext.

What I'm not sure is whether test_cext should be modified to skip any Windows build, or just PGO, or if it ought to work in release/pgo mode and the PGO builder is just highlighting something on my worker.

**Review by vstinner — APPROVED** [review]
LGTM

**Review by mdboom — APPROVED** [review]
LGTM

**Comment by itamaro** [comment]
@db3l `test_cext` passed, but 5 other tests failed (test_call test_class test_functools test_int test_ssl)

logs: https://buildbot.python.org/#/builders/1622/builds/1/steps/5/logs/stdio

**Pull request merged**
