### PR TITLE
Add s390x Fedora worker

### PR DESCRIPTION
**Pull request by edelsohn**

### CODE REVIEW

**Comment by pablogsal** [comment]
Check https://github.com/python/buildmaster-config/pull/160#issuecomment-578235950

**Comment by pablogsal** [comment]
Can you rebase this?

**Comment by pablogsal** [comment]
@edelsohn Sadly, there are still merge conflicts that need to be resolved before I can land this :(

**Comment by edelsohn** [comment]
@pablogsal I resolved the conflicts and committed the merge into the pull request.

**Comment by pablogsal** [comment]
Configuration deployed!

**Pull request merged**
