### PR TITLE
AIX passes 3.8 tests

### PR DESCRIPTION
**Pull request by aixtools**
AIX passes master and 3.8 - as is. The 3.7 backports are finished and awaiting review and merge.

### CODE REVIEW

**Comment by aixtools** [comment]
Hi - these are the PR (backports) needed to also have 3.7 in the green. At least asof a month ago.

[3.7] bpo-34373: Fix time.mktime() on AIX (GH-12726)
CLA signed awaiting review
#14242 opened 26 days ago by aixtools
updated 26 days ago
[3.7] bpo-34720: Fix test_importlib.test_bad_traverse for AIX (GH-9391)
CLA signed awaiting review
#14238 opened 26 days ago by aixtools
updated 26 days ago
[3.7] bpo-11192: Fix test_socket.py for AIX (GH-8954)
CLA signed awaiting review type-tests
#14237 opened 26 days ago by aixtools
updated 26 days ago
[3.7] bpo-34711: Return HTTPStatus.NOT_FOUND if path.endswith(/) and not a directory (GH-9687)
CLA signed awaiting review
#14197 opened 27 days ago by aixtools
updated 27 days ago
[3.7] bpo-35704: Fix test_shutil result for 32-bit AIX when MAXDATA < 0x20000000 [GH-11500]
CLA signed awaiting review type-tests 

Thanks for your consideration!

**Comment by zware** [comment]
I'm not ready to merge this change if there are still changes to be merged to 3.7 for tests to pass there.  I'm fine with enabling 3.8; not 3.7 until those PRs are merged.

**Comment by aixtools** [comment]
> 
> 
> I'm not ready to merge this change if there are still changes to be merged to 3.7 for tests to pass there. I'm fine with enabling 3.8; not 3.7 until those PRs are merged.

Modified the master.cfg to ignore both 2.7 and 3.7 branches.

**Comment by aixtools** [comment]
Requesting this gets merged. The longer the wait the greater the chance a regression gets missed.

**Comment by zware** [comment]
Sorry for the delay, I finally found a minute to get this merged and deployed.

**Pull request merged**
