### PR TITLE
Reconfigure the raspbian bot to avoid test timeouts

### PR DESCRIPTION
**Pull request by gpshead**
test_tools and test_peg_generator cannot complete within 15 minutes on an rpi4 --with-pydebug build.

### CODE REVIEW

**Comment by gpshead** [comment]
holding off.  the crashing may not have been an OOM.  investigating.  I don't have the console logs to see the root cause right now.

**Comment by gpshead** [comment]
found my stability issue. I had switched power supplies a month or two ago; the USB port on my UPS is lame and insufficient for a pi4. back to the power brick it is.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
@gpshead Could you rebase the PR?

**Comment by gpshead** [comment]
> @gpshead Could you rebase the PR?

done I think.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
I will redeploy this soon

**Pull request merged**
