### PR TITLE
Add additional builders for the s390x workers

### PR DESCRIPTION
**Pull request by stratakis**

### CODE REVIEW

**Comment by stratakis** [comment]
@edelsohn

**Comment by stratakis** [comment]
Note that for the clang builds, the clang and compiler-rt packages need to be installed at the fedora workers.

**Comment by edelsohn** [comment]
Clang and compiler-rt has been installed on RHEL8, Fedora 31, and Rawhide systems.
Clang-3.9 has been installed on the Debian system.

**Comment by stratakis** [comment]
Note here that I haven't added the clang builds on the RHEL systems, as at least personally I haven't tested compiling python with clang on a rhel based distro, not sure how common that is.

Also I didn't add the clang builds on the Debian systems, but I could definitely add some more configs there if you would like. Note that the compiler-rt package is required for the [address sanitizer](https://clang.llvm.org/docs/AddressSanitizer.html) builds of clang which I have enabled for rawhide and fedora stable.

**Comment by edelsohn** [comment]
compiler-rt is installed on RHEL8, Fedora, Rawhide.

**Comment by stratakis** [comment]
So @edelsohn are you ok with adding those configs on the workers?

Summarizing here the additional builds that will be triggered on every commit:

On Fedora rawhide and Fedora stable:

Reference leaks
Clang with address sanitizer
Clang with installed python
Link time optimizations
Link time optimizations and Profile guided optimizations

On RHEL7 and RHEL8:

Reference leaks
Link time optimizations
Link time optimizations and Profile guided optimizations

**Comment by edelsohn** [comment]
Let's give it a try and see what happens.  We'll monitor it and scale back the builds or scale up the resources if necessary.

**Comment by vstinner** [comment]
I deployed the updated configuration. New s390x workers should pop up at https://buildbot.python.org/all/#/builders

**Pull request merged**
