### PR TITLE
Disable JUnit XML output

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Comment by vstinner** [comment]
@pablogsal @ambv: I chose to keep the code to be able to reenable quickly upload, if someone needs it tomorrow. If you prefer, I can just remove the code.

**Comment by encukou** [comment]
Is there a different way to get machine-readable info on which test failed?

**Comment by vstinner** [comment]
> Is there a different way to get machine-readable info on which test failed?

I don't think so. I propose to disable the XML output since nobody uses it. Except if you use it?

**Comment by encukou** [comment]
Well, I have a semi-working ad-hoc tool, which I haven't used it in a while but has been helpful in the past. I don't know if that counts as using the XML.

But I'm afraid that if I need it again, I'll need it for past dumps, so reenabling the uploads won't help much.

**Comment by vstinner** [comment]
@encukou: If you may still use the XML output, let's keep it for now.

**Pull request closed without merging**
