### PR TITLE
AMD64 FreeBSD CURRENT Shared 3.x: use long timeout

### PR DESCRIPTION
**Pull request by vstinner**
Change timeout from 20 min to 30 min.

### CODE REVIEW

**Comment by vstinner** [comment]
cc @pablogsal @koobs

**Comment by koobs** [comment]
@vstinner Successful 3.x tests from 20 days ago were averaging 25 minutes. No VM changes (resource wise) have been made to the worker VM. 

 1) What's happened in the 3.x branch/tests since then?
 2) Is test_timeout a per test timeout?
 3) Could these longer test run times be mostly attributed to "warning / failure then pass" runs effectively doubling test time?
 4) The last 3.x failure shows:

```
0:45:26 load avg: 3.31 [419/420/5] test_tokenize crashed (Exit code 1) -- running: test_lib2to3 (9 min 5 sec)
Timeout (0:15:00)!
Thread 0x0000000800ac2000 (most recent call first):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/tokenize.py", line 484 in _tokenize
```

Wont increasing the timeout just increase the time it takes to report the failure, since a crash is presumably the original/preceding/root cause?

**Comment by vstinner** [comment]
> @vstinner Successful 3.x tests from 20 days ago were averaging 25 minutes.

Are you sure that the final result is "Tests result: SUCCESS"? Latest build:
https://buildbot.python.org/all/#/builders/168/builds/617

```
Timeout (0:15:00)!
Thread 0x0000000800ac2000 (most recent call first):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/tokenize.py", line 525 in _tokenize
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_tokenize.py", line 1528 in <listcomp>
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_tokenize.py", line 1528 in check_roundtrip
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_tokenize.py", line 1627 in test_random_files
```

@koobs: It's your buildbot worker, no?

**Comment by pablogsal** [comment]
I am going to merge this one, as the test suite has become slower recently and we have a lot of random failures that are hiding other more important problems due to timeouts.

**Comment by vstinner** [comment]
@pablogsal: Did you deploy the new config?

**Comment by pablogsal** [comment]
@vstinner Yes :)

**Comment by vstinner** [comment]
Cool. Let's see how things are going with my attempt to hack the buildbot
config :-)

**Comment by koobs** [comment]
> > @vstinner Successful 3.x tests from 20 days ago were averaging 25 minutes.
> 
> Are you sure that the final result is "Tests result: SUCCESS"? Latest build:
> https://buildbot.python.org/all/#/builders/168/builds/617

I referred to the last successful (green, not warn, or fail-then-pass or fail) build, which was 20 days ago.

**Comment by vstinner** [comment]
@koobs Sorry, I misunderstood thhe comment. I don't know why the tests take longer. Either the buildbot worker became slower or more tests were added to Python.

**Pull request merged**
