### PR TITLE
Add Windows 11 build worker

### PR DESCRIPTION
**Pull request by jkloth**

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Wow, nice! Thanks for the PR @jkloth .

I am going to deploy the changes. Could you confirm that the builder is operative and running?

**Comment by jkloth** [comment]
Up and running (and failing as expected :)

-- 
Jeremy Kloth

**Comment by pablogsal** [comment]
> (and failing as expected :)

Ah, I though this was expected to succeed. In that case I will mark it as UNSTABLE for now

**Comment by vstinner** [comment]
> Ah, I though this was expected to succeed. In that case I will mark it as UNSTABLE for now

In general, I would suggest to always start with UNSTABLE, and only mark as STABLE after 1 week of successful builds.

**Comment by jkloth** [comment]
> Ah, I though this was expected to succeed. In that case I will mark it as UNSTABLE for now

It would succeed once https://bugs.python.org/issue45354 (submitted at the same time as the buildbot) is resolved.  It seems there is a shortage of developers willing/able to handle Windows-only items.

**Comment by pablogsal** [comment]
> It seems there is a shortage of developers willing/able to handle Windows-only items.

Indeed. Maybe you can convince @zooba to take a look :)

**Comment by pablogsal** [comment]
Also, one of the problems is to get a Windows 11 machine :(

**Comment by pablogsal** [comment]
I would try to install it on my main computer and take a look but there is all the TMP shenanigans and I don't want to deal with that right now.

**Comment by jkloth** [comment]
> Also, one of the problems is to get a Windows 11 machine :(

That was my point in getting this buildbot up and running prior to the public release of Win11 on Oct 5th

**Pull request merged**
