### PR TITLE
Create WARNING_PATTERN regex to catch warnings

### PR DESCRIPTION
**Pull request by haypo**
Define a regular expression to catch different warnings, errors and
bugs specific to CPython.

### CODE REVIEW

**Comment by haypo** [comment]
I didn't test my change.

I'm not sure about the last warning, PyErr_WriteUnraisable(), maybe we will catch too many warnings. Is it an issue? If yes, I can remove it. If not, we may remove it later if it's more noisy than useful.

**Comment by haypo** [comment]
(oops, I clicked on the wrong button, I didn't want to close this PR.)

**Comment by haypo** [comment]
cc @zware

**Comment by haypo** [comment]
Documentation of the warningPattern parameter:
http://docs.buildbot.net/latest/manual/cfg-buildsteps.html#compile

**Comment by haypo** [comment]
I want to get warnings from the "tests" step. I'm not sure that my change is correct.

**Comment by zware** [comment]
I think `warnOnWarnings=True` on the `Test()` steps, with this regex, would cover that.  The default regex should be fine on the `Compile()` steps.

**Comment by haypo** [comment]
Another interesting pattern: "Unhandled exception in thread" logged by the low-level t_bootstrap() function which manages the lifetime of a Python thread.

**Comment by haypo** [comment]
> I think warnOnWarnings=True on the Test() steps, with this regex, would cover that. The default regex should be fine on the Compile() steps.

I checked buildbot code: Compile and Step classes have the same base class, and both support warningPattern. I updated my PR.

I created a new Test class to limit changes to avoid mistakes in the future in a new buildbot is added.

**Comment by haypo** [comment]
> warnOnWarnings=True

I don't want to make the buildbot fail on these new warnings. I will first analyze them and try to fix some of them. It's ok to get *warnings* ;-)

**Comment by zware** [comment]
> I don't want to make the buildbot fail on these new warnings.

Right, there's `failOnWarnings` for that :).  `warnOnWarnings` should just make it orange rather than green, but still a pass.

**Comment by haypo** [comment]
> Looks fine to me, we'll give it a try.

Oh, I'm suprised: it seems like my change worked :-) Did you have to run a chef/puppet job for that? Or reload buildbot configuration manually? Or everything is automated?

Example of catched "Fatal Python error: Aborted":

http://buildbot.python.org/all/builders/AMD64%20OpenIndiana%203.x/builds/467/steps/test/logs/warnings%20%2817%29

Example of catched "Warning -- files was modified by test_distutils":

http://buildbot.python.org/all/builders/AMD64%20Windows10%203.x/builds/595/steps/test/logs/warnings%20%281%29

These warnings are very valuable to me!

**Pull request merged**
