### PR TITLE
Delete my armv7 worker due to hardware issues.

### PR DESCRIPTION
**Pull request by gpshead**

### CODE REVIEW

**Comment by gpshead** [comment]
apparently `master/custom/builders.py` also needs an edit.  The github web UI makes this seemingly impossible.

I don't want to have to checkout and manage a forked repository of my own just to make trivial configuration edits.

These really belong all in one file.

**Comment by zware** [comment]
The edit can be done in the web UI by navigating to the file from the tree view of your branch and clicking the edit icon.  But there is still significant fixing to be done to this config that I haven't had time to get back to yet :(

**Comment by zware** [comment]
Btw, is this worker coming back, or it's gone for good?

**Comment by gpshead** [comment]
Lets consider this one gone for good given the state of the hardware.  I've got one or two new arm bots that i'll be adding soon.

**Pull request merged**
