### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by pablogsal**

### CODE REVIEW

**Comment by vstinner** [comment]
Not good:

```
error while parsing config file:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/twisted/internet/defer.py", line 167, in maybeDeferred

    result = f(*args, **kw)

  File "/home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/buildbot/scripts/checkconfig.py", line 57, in checkconfig

    return _loadConfig(basedir=basedir, configFile=configFile, quiet=quiet)

  File "/home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/buildbot/scripts/checkconfig.py", line 27, in _loadConfig

    config.FileLoader(basedir, configFile).loadConfig()

  File "/home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/buildbot/config.py", line 151, in loadConfig

    filename, config_dict = loadConfigDict(

--- <exception caught here> ---

  File "/home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/buildbot/config.py", line 114, in loadConfigDict

    execfile(filename, localDict)

  File "/home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/twisted/python/compat.py", line 225, in execfile

    exec(code, globals, locals)

  File "/home/travis/build/python/buildmaster-config/master/master.cfg", line 423, in <module>

    reporters.GitHubStatusPush(

  File "/home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/buildbot/reporters/base.py", line 36, in __init__

    super().__init__(*args, **kwargs)

  File "/home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/buildbot/util/service.py", line 189, in __init__

    self.checkConfig(*args, **kwargs)

  File "/home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/buildbot/reporters/github.py", line 51, in checkConfig

    super().checkConfig(generators=generators, **kwargs)

builtins.TypeError: checkConfig() got an unexpected keyword argument 'builders'
```

**Comment by pablogsal** [comment]
I had to follow the http://docs.buildbot.net/current/manual/upgrading/3.0-upgrade.html guide to migrate to buildbot 3.0

**Comment by pablogsal** [comment]
Alea iacta est

**Comment by vstinner** [comment]
Oh wow, thanks for the hacks!

**Pull request merged**
