### PR TITLE
[ON HOLD] Add a RHEL8 s390x worker

### PR DESCRIPTION
**Pull request by stratakis**

### CODE REVIEW

**Comment by pablogsal** [comment]
@stratakis Do you have a worker password already?

**Comment by stratakis** [comment]
I've got worker passwords for the rest of my buildbots (different for each), but notpassword has been generated for me since the new config was deployed. Can I reuse a pass from one of my workers or does a new one have to be generated?

**Comment by zware** [comment]
With some recent changes to the config (namely the one that made the worker setup more public), you can have a single password for all workers or a unique password per worker.  You currently have both; your RHEL{7,8}-x86_64 and fedora-stable workers each have their own password while your fedora-rawhide worker is using your "owner" password.  We can generate a new one for this worker, or you can use the same one as fedora-rawhide as soon as this is deployed, whichever you would prefer.

**Comment by stratakis** [comment]
Putting it on hold for the time being.

**Comment by vstinner** [comment]
@stratakis: Contact me directly. I can provide you a password and merge this PR, once the worker is ready on your side.

**Comment by stratakis** [comment]
Closing this in favor of #160

**Pull request closed without merging**
