### PR TITLE
Add parallelism for the s390x workers

### PR DESCRIPTION
**Pull request by stratakis**

### CODE REVIEW

**Comment by stratakis** [comment]
The workers have four cores, so this PR essentially adds the -j6 flag when running the tests.

**Comment by stratakis** [comment]
@edelsohn

**Comment by edelsohn** [comment]
This also can be done for the Debian Z and SLES Z buildbots, if you want.

**Comment by stratakis** [comment]
I'll rebase. That should cut the build time significantly.

**Pull request merged**
