### PR TITLE
FIPS builders should compile only 3.12+ branches

### PR DESCRIPTION
**Pull request by stratakis**

### CODE REVIEW

**Comment by stratakis** [comment]
@encukou

**Comment by stratakis** [comment]
3.12+ branches work better with FIPS since https://github.com/python/cpython/pull/20380/files

As the multiprocessing fix is quite invasive for backport, it makes sense to keep testing FIPS on 3.12+

**Review by vstinner — APPROVED** [review]
LGTM.

@encukou: Would you mind to double check?

**Comment by encukou** [comment]
Thank you, this looks like the best solution!

Today is release day -- a bad time to restart Buildbot. I'll test & merge after the release.

**Pull request merged**
