### PR TITLE
Add release dashboard to the buildbot menu

### PR DESCRIPTION
**Pull request by pablogsal**
dsfsdf
Screenshot from 2020-01-19 19-36-11

### CODE REVIEW

**Comment by pablogsal** [comment]
Screenshot from 2019-10-02 01-55-36

**Comment by pablogsal** [comment]
Screenshot from 2020-01-19 19-36-11

**Comment by zware** [comment]
I've not looked in detail because I'm not familiar with how most of this works :).  However, I'm in favor of the idea, so I'd say go for it when you're confident in the code.

**Comment by pablogsal** [comment]
Thanks, @zware!

I tested it on the master test and we can always iterate in the future :)

**Pull request merged**
